### ISSUE TITLE
libgnome-keyring does not exist on Ubuntu 20.04

### ISSUE THREAD

**Issue by simon816** [Yeregorix/java-keyring#2]
```
libgnome-keyring.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libgnome-keyring.so) not found in resource path ([...])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at net.smoofyuniverse.keyring.gnome.GNOMEKeyringLib.<clinit>(GNOMEKeyringLib.java:13)
	at net.smoofyuniverse.keyring.gnome.GNOMEKeyring.<init>(GNOMEKeyring.java:38)
```
The new way to communicate with GNOME Keyring is via libsecret: https://wiki.gnome.org/Projects/Libsecret
> libsecret replaces libgnome-keyring. 

There is a migration guide here https://developer.gnome.org/libsecret/unstable/migrating.html

Besides linking to libsecret, it is also possible to use the D-Bus interface directly e.g. https://github.com/swiesend/secret-service

**Comment by Yeregorix** [comment]
Thanks for reporting! I'm busy these days but I will look at this asap.

**Comment by Yeregorix** [comment]
I have a working piece of code using Libsecret in C, now I need to port it to Java.

**Comment by simon816** [comment]
Thanks!
